version: '3'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=HardPassword1234@"
      - "MSSQL_PID=Developer"
    volumes:
      - ./data:/var/opt/mssql/data