ARG MSSQL_VERSION

# https://www.docker.elastic.co/
FROM mcr.microsoft.com/mssql/server:${MSSQL_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
